# Generated by Django 4.1.7 on 2023-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0004_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
