# Generated by Django 4.1.7 on 2023-03-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.ManyToManyField(to='accounts.interest', verbose_name='Intereses'),
        ),
    ]
